"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import data from "./radar-data.json";

type Evidence={id:string;publisher:string;text:string;url:string};
type RadarEvent={event_id:string;title:string;summary:string;score:number;trend:string;independent_count:number;news_count:number;x_count:number;categories:string[];why_watch:string;items:Evidence[]};
type History={date:string;open:number;high:number;low:number;close:number;volume:number};
type Stock={rank:number;security_id:string;name:string;ticker:string;market:string;replay_date:string;close:number;change_pct:number;current_volume:number;median_volume_20d:number;volume_ratio:number;liquidity_level:string;display_rules:string[];raw_metrics:Record<string,number|boolean|string|null>;why_selected:string;consecutive_days:number;history?:History[];disclosures?:Array<{subject:string;announced_at:string|null;event_date:string|null;official_url:string}>};
type Persistent={security_id:string;name:string;ticker:string;market:string;longest_consecutive:number};
type QueueState=Record<string,{status:"queued"|"ignored";note:string}>;
const payload=data.stock_workbench as unknown as {rule_version:string;replay_date:string;data_status:string;participating:{TWSE:number;TPEX:number};top20:Stock[];early_momentum:Stock[];persistent:Persistent[];details:Record<string,Stock>};
const events=data.events as RadarEvent[];const QUEUE_KEY="ben-stock-radar.public-queue.v1";const labels:Record<string,string>={NEW:"新出现",HEATING:"快速升温",SUSTAINED:"持续发酵",COOLING:"开始降温"};
const fmt=(value:number)=>new Intl.NumberFormat("zh-TW").format(value);const pct=(value:number)=>`${value>=0?"+":""}${value.toFixed(2)}%`;
function exportSelection(queue:QueueState,kind:"json"|"csv"){const rows=events.filter(e=>queue[e.event_id]?.status==="queued").map(e=>({event_id:e.event_id,title:e.title,score:e.score,note:queue[e.event_id]?.note||""}));const content=kind==="json"?JSON.stringify(rows,null,2):"\uFEFFevent_id,title,score,note\n"+rows.map(row=>Object.values(row).map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([content],{type:kind==="json"?"application/json":"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`ben-radar-selection.${kind}`;link.click();URL.revokeObjectURL(url)}

function Chart({stock}:{stock:Stock}){const ref=useRef<HTMLCanvasElement>(null);const[range,setRange]=useState(22);useEffect(()=>{const canvas=ref.current,rows=(stock.history||[]).slice(-range);if(!canvas||!rows.length)return;const w=canvas.clientWidth,h=420,dpr=window.devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext("2d");if(!c)return;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);const p={l:54,r:18,t:22},ph=270,vt=310,vh=82,m=stock.raw_metrics,markers=[Number(m.prior_20d_high||0),Number(m.prior_40d_high||0)].filter(Boolean),max=Math.max(...rows.map(r=>r.high),...markers),min=Math.min(...rows.map(r=>r.low),...markers),span=max-min||1,mv=Math.max(...rows.map(r=>r.volume),1),y=(v:number)=>p.t+(max-v)/span*ph,step=(w-p.l-p.r)/rows.length,body=Math.max(2,Math.min(9,step*.62));c.font="11px system-ui";c.strokeStyle="#e5ebf1";c.fillStyle="#77879a";for(let i=0;i<5;i++){const yy=p.t+ph*i/4;c.beginPath();c.moveTo(p.l,yy);c.lineTo(w-p.r,yy);c.stroke();c.fillText((max-span*i/4).toFixed(2),4,yy+4)}([[m.prior_20d_high,"#7c3aed","20D"],[m.prior_40d_high,"#f59e0b","40D"]] as Array<[number|string|boolean|null|undefined,string,string]>).forEach(([raw,color,label])=>{const v=Number(raw||0);if(!v)return;const yy=y(v);c.save();c.setLineDash([6,5]);c.strokeStyle=color;c.beginPath();c.moveTo(p.l,yy);c.lineTo(w-p.r,yy);c.stroke();c.restore();c.fillStyle=color;c.fillText(`${label} ${v.toFixed(2)}`,p.l+5,yy-5)});rows.forEach((r,i)=>{const x=p.l+step*(i+.5),color=r.close>=r.open?"#e23b3b":"#14956f";c.strokeStyle=color;c.fillStyle=color;c.beginPath();c.moveTo(x,y(r.high));c.lineTo(x,y(r.low));c.stroke();const top=y(Math.max(r.open,r.close)),bh=Math.max(1,Math.abs(y(r.open)-y(r.close)));c.fillRect(x-body/2,top,body,bh);const bar=r.volume/mv*vh;c.globalAlpha=.72;c.fillRect(x-body/2,vt+vh-bar,body,bar);c.globalAlpha=1});c.fillStyle="#77879a";[0,Math.floor((rows.length-1)/2),rows.length-1].forEach(i=>c.fillText(rows[i].date.slice(5),p.l+step*(i+.5)-14,h-5))},[stock,range]);return <section className="drawer-chart"><header><div><h3>真实日K与成交量</h3><p>水平虚线为 Replay 日之前的 20D / 40D 高点</p></div><nav><button className={range===22?"active":""} onClick={()=>setRange(22)}>1M</button><button className={range===66?"active":""} onClick={()=>setRange(66)}>3M</button></nav></header><canvas ref={ref}/><div className="chart-legend"><span><i className="up"/>上涨</span><span><i className="down"/>下跌</span><span><i className="line20"/>prior 20D high</span><span><i className="line40"/>prior 40D high</span></div></section>}

function Drawer({stock,onClose}:{stock:Stock|null;onClose:()=>void}){if(!stock)return null;return <div className="stock-drawer-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><aside className="stock-drawer" role="dialog" aria-modal="true"><button className="drawer-close" onClick={onClose}>×</button><header><div><p className="eyebrow">STOCK DETAIL · {stock.market}</p><h2>{stock.name}</h2><p>{stock.ticker} · {stock.security_id}</p></div><div className="drawer-status"><strong>EOD</strong><span>数据对应交易日 {stock.replay_date}</span></div></header><section className="drawer-metrics">{[["实际成交量",`${fmt(stock.current_volume)} 股`,true],["RVOL",`${stock.volume_ratio.toFixed(2)}×`,true],["20日中位量",`${fmt(stock.median_volume_20d)} 股`,false],["收盘价",stock.close.toFixed(2),false],["涨跌幅",pct(stock.change_pct),false],["流动性",stock.liquidity_level,false]].map(([l,v,primary])=><div className={primary?"primary":""} key={String(l)}><span>{l}</span><strong>{v}</strong></div>)}</section><Chart stock={stock}/><section className="drawer-explanation"><div><h3>异动解释</h3><div className="rule-chips">{stock.display_rules.map(rule=><i key={rule}>{rule}</i>)}</div><p>{stock.why_selected}</p><details><summary>raw_metrics</summary><pre>{JSON.stringify(stock.raw_metrics,null,2)}</pre></details></div><div><h3>信息催化剂</h3>{stock.disclosures?.length?stock.disclosures.map(item=><a key={`${item.subject}-${item.announced_at}`} href={item.official_url} target="_blank" rel="noreferrer"><b>{item.subject}</b><span>{item.announced_at||item.event_date||"日期未知"} · MOPS ↗</span></a>):<p>信息催化剂：尚未确认</p>}</div></section></aside></div>}

export default function Home(){const[active,setActive]=useState<Stock|null>(null),[queue,setQueue]=useState<QueueState>({}),[category,setCategory]=useState("ALL");useEffect(()=>{try{setQueue(JSON.parse(localStorage.getItem(QUEUE_KEY)||"{}"))}catch{setQueue({})}},[]);useEffect(()=>{localStorage.setItem(QUEUE_KEY,JSON.stringify(queue))},[queue]);useEffect(()=>{document.body.style.overflow=active?"hidden":"";return()=>{document.body.style.overflow=""}},[active]);const visible=useMemo(()=>events.filter(event=>(category==="ALL"||event.categories.includes(category))&&queue[event.event_id]?.status!=="ignored"),[category,queue]);const open=(id:string)=>setActive(payload.details[id]||null),categories=[["ALL","全部"],["TW","台股"],["US","美股"],["AI","AI 科技"],["MACRO","宏观"]];return <main data-workbench-version="ben-stock-workbench.v0.1"><header className="topbar"><a className="brand" href="#top"><span className="brand-mark">B</span><span>BEN Radar</span><small>股票工作台</small></a><nav><a className="active" href="#market">市场异动</a><a href="#radar">机会雷达</a><a href="#method">规则说明</a></nav><div className="live-pill">公开快照</div></header>
<section className="workbench-hero" id="top"><div><p className="eyebrow">BEN RADAR · ANOMALY ENGINE {payload.rule_version}</p><h1>⚡ 市场异动</h1><p>用自身20日基准辨识异常放量、区间突破与量价共振；以下不是交易建议。</p></div><div className="workbench-status"><strong>{payload.data_status}</strong><span>数据对应交易日：{payload.replay_date}</span><small>TWSE {payload.participating.TWSE} · TPEx {payload.participating.TPEX}</small></div></section>
<section className="market-anomaly-grid" id="market">{payload.top20.map(s=><button className="market-anomaly-card" key={s.security_id} onClick={()=>open(s.security_id)}><span className="stock-rank">{String(s.rank).padStart(2,"0")}</span><span className="stock-identity"><b>{s.name}</b><small>{s.ticker} · {s.market}</small></span><span className="volume-primary"><small>实际成交量</small><b>{fmt(s.current_volume)}</b><em>股</em></span><span className="rvol-primary"><small>RVOL</small><b>{s.volume_ratio.toFixed(2)}×</b><em>20日中位量 {fmt(s.median_volume_20d)}</em></span><span className={`stock-move ${s.change_pct>=0?"positive":"negative"}`}><b>{pct(s.change_pct)}</b><small>收盘 {s.close.toFixed(2)}</small></span><span className={`liquidity liquidity-${s.liquidity_level.toLowerCase()}`}>{s.liquidity_level}</span><span className="rule-chips">{s.display_rules.map(rule=><i key={rule}>{rule}</i>)}</span><span className="stock-why">{s.why_selected}</span>{s.consecutive_days>=2&&<span className="streak-badge">连续异动 {s.consecutive_days} 日</span>}<span className="card-arrow">›</span></button>)}</section>
<section className="anomaly-groups"><article><header><div><p className="eyebrow">EARLY MOMENTUM</p><h3>潜在先行动能</h3></div><span>{payload.early_momentum.length}</span></header><p>涨幅不大，但放量与突破规则已同时出现。此分组不改变排名。</p><div>{payload.early_momentum.length?payload.early_momentum.map(s=><button key={s.security_id} onClick={()=>open(s.security_id)}><b>{s.name}</b><span>{pct(s.change_pct)} · RVOL {s.volume_ratio.toFixed(2)}×</span></button>):<small>本日 Top20 没有符合条件的先行动能。</small>}</div></article><article><header><div><p className="eyebrow">PERSISTENT</p><h3>持续异动</h3></div><span>{payload.persistent.length}</span></header><p>最近6个完整交易日中，连续至少2日进入 Top20。</p><div>{payload.persistent.slice(0,8).map(s=><span className="persistent-row" key={s.security_id}><b>{s.name}</b><em>{s.ticker} · {s.market}</em><strong>连续 {s.longest_consecutive} 日</strong></span>)}</div></article></section>
<section className="opportunity-intro" id="radar"><div><p className="eyebrow">CONTENT OPPORTUNITY RADAR</p><h2>机会雷达</h2><p>市场异动之外，保留既有新闻与 X Evidence 选题流。</p></div></section><div className="controls"><div className="tabs">{categories.map(([key,label])=><button className={category===key?"selected":""} key={key} onClick={()=>setCategory(key)}>{label}</button>)}</div></div>
<section className="event-list">{visible.map((e,index)=><article className="event-card" key={e.event_id}><div className="rank">{String(index+1).padStart(2,"0")}</div><div className="event-main"><div className="badges">{e.categories.map(v=><span key={v}>{v}</span>)}<span>● {labels[e.trend]||e.trend}</span></div><h3>{e.title}</h3><p className="summary">{e.summary}</p><div className="metrics"><span><b>{e.independent_count}</b> 独立来源</span><span><b>{e.news_count}</b> 家媒体</span><span><b>{e.x_count}</b> 个 X 账号</span></div><div className="watch"><strong>为什么值得关注</strong><p>{e.why_watch}</p></div><details><summary>查看 Evidence {e.items.length}</summary><div className="evidence-list">{e.items.map(item=><article key={item.id}><b>{item.publisher}</b><p>{item.text}</p><a href={item.url} target="_blank" rel="noreferrer">查看原始 Evidence ↗</a></article>)}</div></details></div><aside className="score-panel"><span>内容机会分</span><strong>{e.score}<small>/100</small></strong><button onClick={()=>setQueue(q=>({...q,[e.event_id]:{status:"queued",note:""}}))}>加入选题池</button><button className="ghost" onClick={()=>setQueue(q=>({...q,[e.event_id]:{status:"ignored",note:""}}))}>忽略</button></aside></article>)}</section>
<section className="queue-panel"><div><p className="eyebrow">浏览器本地保存</p><h2>我的选题池</h2><p>{Object.values(queue).filter(item=>item.status==="queued").length} 个已保存选题。没有服务器写入。</p></div><div><button onClick={()=>exportSelection(queue,"json")}>导出 JSON</button><button onClick={()=>exportSelection(queue,"csv")}>导出 CSV</button><button className="ghost" onClick={()=>setQueue({})}>恢复全部</button></div></section><section className="method" id="method"><p className="eyebrow">透明规则</p><h2>这不是交易信号</h2><div><p><strong>排名</strong>只使用规则命中数量与每条规则异常程度，不使用旧 0–100 股票评分。</p><p><strong>成交量</strong>以实际股数显示；RVOL 对比该股 Replay 日之前20个交易日的成交量中位数。</p><p><strong>数据状态</strong>当前为 {payload.data_status}，对应交易日 {payload.replay_date}，不宣称实时。</p></div></section><footer><span>BEN Radar · 股票工作台</span><span>公开只读快照 · 非投资建议</span></footer><Drawer stock={active} onClose={()=>setActive(null)}/></main>}
